### ISSUE TITLE
If I set viewDate the month fwd/prev navigation buttons don't work

### ISSUE THREAD

**Issue by mmw** [zippyui/react-date-picker#25]
Great plugin! Thanks for creating it. I'm implementing the plugin for a min and max range, when one field is selected I populate the plugin with the values and show it. If I have a min date in may and then set a max date in june when I click on the min date to edit the picker shows june, I'd like it to be set on the current date. Using viewDate accomplishes this, however the nav buttons no longer work. Don't see any JS errors either.

**Comment by zippyui-react** [comment]
I haven't quite grasped the explanation. We really want to help with this, so can you please show a code sample with what you want to accomplish (maybe a live example on jsbin or similar). Thanks

**Comment by mateusz-wijas** [comment]
Sorry, that was kind of wall of text. Hope this explains my issue better.

I'm requiring date picker in my component:

`var DatePicker = require('react-date-picker');`

Then using it like so:
```
<DatePicker
  className={classes}
  date={pickerDate}
  viewDate={pickerDate}
  minDate={pickerMinDate}
  maxDate={pickerMaxDate}
  onChange={pickerOnChange}
/>
```

My values are based on state changes. The problem is `viewDate`. I set it to the same value as `date` and it works. It makes the picker open on the date that I passed. The only problem is if I click on the arrows to advance to the next month (or previous month) nothing happens.

For example, if I open the picker now I'm in May and I can't choose a day in June because I can't advance the monthly view forward. If I remove `viewDate` I am able to choose a day in June because I'm able to advance to that month.

This component is being reused. I'm using it for more than one day input, I would like it to show June when I click an input with a June date and open in May when I click on an input in a May day.

**Comment by zippyui-react** [comment]
The `viewDate` prop is a controlled prop. If this is not what you want, but want uncontrolled behavior, use `defaultViewDate` or simply skip specifying the viewDate (it will default to the given date to start with). If you instead want to control the `viewDate` prop, make sure you specify an `onViewDateChange` function  prop and update the `viewDate` accordingly.

**Comment by mateusz-wijas** [comment]
Ok, I understand how `viewDate` is intended to work. It's strange that I can click on the month and get a list of months to choose from then get forced back to the controlled date month. I'd expect that view to not be presented to me.

So trying to using `defaultViewDate` doesn't work as expected. I'm passing a `moment` object to `defaultViewDate` for one month but it's still displaying the last month I had viewed. Possibly relevant but the `date` prop works exactly as I expect.. it highlights the correct date in both cases.

For example: I open my first input with the date picker and choose May 11. Then open the second one and choose June 6. If I select the first input again the date picker will open on June instead of May, however May 11 is selected as the date when I navigate back to May.

**Comment by mateusz-wijas** [comment]
Maybe this is a better example. Using just one input with the date picker. First I choose May 11, then use the arrows to advance the date picker to August. After that I reinitialize the date picker with the May 11 date but the month view stays at August instead of changing to May to highlight the current date.

**Comment by mateusz-wijas** [comment]
@zippyui-react Any possible fixes for this? or should I use two separate date picker objects? I was hoping to avoid that.

**Comment by zippyui-react** [comment]
Can you please post a simplified example of this part of your app (maybe here or jsbin)? If you're reusing the picker for both the inputs, and want to use `defaultViewDate`, you can use `setViewDate` https://github.com/zippyui/react-date-picker/blob/master/src/index.jsx#L335 on the picker instance to navigate to whatever date you want.

Since you're reusing the picker, the defaultViewDate will follow the navigation from the last interaction, so will remain at August of the second picker in your above example. And when you reuse the input again on the input is on may, since the picker had no interaction, defaultViewDate is pointing to August, since that's set in it's state. You can use `setViewDate` to fix that.

I would really use the controlled `viewDate`, which I would update on any `onViewDateChange` and also on input focus.
If you post a working example on jsbin, I can edit it and make it work with `viewDate`.

**Comment by vn38minhtran** [comment]
My integration sample:

`DateInput.js`

```js
var React = require('react');
var Modal = require('react-modal-bootstrap');
var DatePicker = require('react-date-picker');

require('react-modal-bootstrap/lib/modal.css');
require('react-date-picker/index.css');

var DateInput = React.createClass({
  propTypes: {
    date: React.PropTypes.any,
    placeholder: React.PropTypes.string,
    onChange: React.PropTypes.func
  },
  getDefaultProps: function () {
    return {
      placeholder: 'YYYY-MM-DD'
    };
  },
  getInitialState: function () {
    return {
      date: this.props.date,
      viewDate: this.props.date,
      isOpen: false
    };
  },
  componentWillReceiveProps: function (nextProps) {
    this.setState({
      date: nextProps.date,
      viewDate: nextProps.date
    });
  },
  showModal: function (e) {
    e.preventDefault();
    this.setState({
      isOpen: true
    });
  },
  hideModal: function () {
    this.setState({
      isOpen: false
    });
  },
  handleInputChange: function (e) {
    this.handleChange(e.target.value);
  },
  handlePickerChange: function (dateString) {
    this.handleChange(dateString);
    this.hideModal();
  },
  handleChange: function (dateString) {
    this.setState({
      date: dateString,
      viewDate: dateString
    }, function () {
      if (this.props.onChange) {
        this.props.onChange(this.state.date);
      }
    });
  },
  handlePickerSelect: function (dateString) {
    this.setState({
      viewDate: dateString
    });
  },
  handlePickNav: function (dateString) {
    this.setState({
      viewDate: dateString
    });
  },
  handleViewDateChange: function (dateString) {
    this.setState({
      viewDate: dateString
    });
  },
  render: function () {
    return (
      <div className='date-input'>
        <div className='input-group'>
          <input type='text' className='form-control'
            value={this.state.date} placeholder={this.props.placeholder}
            onChange={this.handleInputChange}/>

          <div className="input-group-btn">
            <button className="btn btn-default"
              onClick={this.showModal}>
              <i className='fa fa-calendar'></i>
            </button>
          </div>
        </div>
        <Modal isOpen={this.state.isOpen} size='modal-sm'
          onRequestHide={this.hideModal}>
          <DatePicker {...this.props} date={this.state.date}
            viewDate={this.state.viewDate} onChange={this.handlePickerChange}
            onSelect={this.handlePickerSelect} onNav={this.handlePickNav}
            onViewDateChange={this.handleViewDateChange}/>
        </Modal>
      </div>
    );
  }
});

module.exports = DateInput;
```

`Other component`

```js
var DateInput = require('./lib/DateInput');
...
<DateInput date={this.state.birth} onChange={this.handleBirthChange}/>
```

***Note:* My project user Bootstrap css & Font Awesome

**Comment by radubrehar** [comment]
Please have a look at #51 if it helps
