### ISSUE TITLE
if 1st day is sunday, first week is entire previous month

### ISSUE THREAD

**Issue by AlbertAlquisola** [zippyui/react-date-picker#55]
If the 1st falls on a sunday, the week is displayed in the 2nd row and the top row is entirely from the previous month. 

![screen shot 2015-12-02 at 9 37 28 am](https://cloud.githubusercontent.com/assets/4959841/11538799/5532a2a0-98d8-11e5-95f6-f66433bd3379.png)

In other calendars, if sunday === 1st of the month, it starts in the top row
![screen shot 2015-12-02 at 9 36 20 am](https://cloud.githubusercontent.com/assets/4959841/11538768/3f3f7f9a-98d8-11e5-9b9f-432c552286a2.png)

**Comment by radubrehar** [comment]
Thanks for reporting. We'll fix this tomorrow

**Comment by radubrehar** [comment]
Our new team member, @bogdanpetru has just solved this. Check it out in `3.1.9` - thanks @bogdanpetru and welcome aboard!

**Comment by AlbertAlquisola** [comment]
awesome, works perfectly! thanks for the quick fix!

**Comment by radubrehar** [comment]
@bogdanpetru is our new core team member and helping a lot push our components a step further! Thanks @bogdanpetru for the great PR #56 with the fix!

@AlbertAlquisola you can still use the old behavior, under the `alwaysShowPrevWeek` flag.
The bug was present not only for Sunday, but whenever the month started on `weekStartDay`.
