### ISSUE TITLE
Setting state doesn't change view

### ISSUE THREAD

**Issue by timcan** [zippyui/react-date-picker#69]
I'm trying to set the date state on the picker after my component mounts (after retrieving data from a document store) in the month view but the picker doesn't navigate it's view to the selected date. I'm using the picker like this:

` 
<DatePicker name="eventDate" date={this.state.eventDate} onChange={this.handleDateChange} />
`

The onChange handler with this:

`
    handleDateChange: function(dateText,moment,event) {
        this.setState({eventDate: moment});
    }
`

And setting the state after the component mounts:

`
componentDidMount: function() {
        this.refs.eventName.focus();
        if( !_.isNil( this.props.params.eventId )) {
            EventService.getEvent(this.props.params.eventId).then(function(event) {
                this.setState({
                    eventName: event.name,
                    eventDate: moment(event.fromDate)
                });
            }.bind(this));
        }
    }
`

Please let me know what I'm missing on having the month view navigate to the selected date. Thanks in advance.

Tim

**Comment by radubrehar** [comment]
Can you provide a minimalistic example showcasing your scenario?

**Comment by tquetano-r7** [comment]
I experiencing something similar as well, however it is infrequent. Here is the simple code:
```
const CalendarTest = ({dateTime, onChangeDate, ...otherProps}) => {
  return (
      <div>
        <MonthView
          date={dateTime}
          dateFormat="YYYY/MM/DD"
          onChange={onChangeDate}
          {...otherProps}
        />
      </div>
  );
};
```
Certain pieces will update when set, but others will not. More accurately, the selector `._1w6eakCtOUZohF-WdK4AEU .react-date-picker__month-view--theme-default .react-date-picker__month-view-day--today-highlight` is updated to the new date, whereas the selector `._1w6eakCtOUZohF-WdK4AEU .react-date-picker__month-view--theme-default .react-date-picker__month-view-day--active .react-date-picker__month-view-day-text` remains on the old one. 

I have noticed the same thing happens when using keyboard navigation ... using the arrows moves the first selector around while the second remains in place until I hit enter, then they align. Maybe that description can help.

**Comment by radubrehar** [comment]
So the behavior is the following: there is an active date, and a selected date.
Using the MonthView as you did, you did not specify an active date, so it uses `defaultActiveDate`, which is uncontrolled. By navigating with the keyboard arrows (or home/end, pageup, page down), you change the active date (you can listen to this as well with `onActiveDateChange`. The moment you hit enter, you change the `date` - which can be controlled, or uncontrolled via `defaultDate`, and calls the `onChange`.

Does it make sense ? :) Let us know how we can further help.

**Comment by radubrehar** [comment]
I suppose you're using the latest v on npm, `5.3.9`

**Comment by tquetano-r7** [comment]
Indeed I am, and adding `activeDate` with the same value as `date` appears to have fixed things. 

That said, keyboard navigation no longer works (likely because I am overriding somethng internally), and having the parent delegate to the child any changes to the date is an expected behavior, so you may consider refactoring so that when `date` changes in props, it also changes the `activeDate`, and otherwise maintains its current internal state management. It would avoid needing to specify `activeDate` as a duplicate prop for this behavior, but also would allow the current behaviors to continue.

**Comment by radubrehar** [comment]
We're considering this.
Although you can easily obtain the same behavior: just specify `activeDate` and listen to `onActiveDateChange`: when it happens, store the activeDate on the parent and re-render the `MonthView`. When `onChange` occurs as well, set both the `date` and the `activeDate` - it's really very flexible.

**Comment by tquetano-r7** [comment]
Oh agreed it will work just fine, at the expense of an additional render cycle. And not trying to impose too much, I love what you've done with this component, I was just adding my two cents :).

**Comment by radubrehar** [comment]
Sure!
It's not quite at the expense of a render, since anyway you have to re-render your app to reflect the date change, so the re-renders will be batched together.
We're glad you enjoy the component. You may also like other components we've made at http://zippyui.com/docs - more to be added very soon :)
